name: SLSA Pipeline

on:
  push:
    branches:
      - master

jobs:
  security-pipeline:
    name: Securiry Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Image Tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Import GPG public key
        run: echo "${{secrets.GPG_PUBLIC_KEY}}" | gpg --import
      - name: Verify commit signature
        run: git log --show-signature -1 | grep "Good signature"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:${{ steps.vars.outputs.tag }}

