name: SLSA Pipeline

on:
  push:
    branches:
      - master

jobs:
  security-pipeline:
    name: Securiry Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Import GPG public key
        run: echo "${{secrets.GPG_PUBLIC_KEY}}" | gpg --import
      - name: Verify commit signature
        run: git log --show-signature -1 | grep "Good signature"
